---
title: "sumbit_Arka"
author: "Arka"
date: "March 12, 2016"
output: html_document
---

```{r load_packages,message=FALSE,warning=FALSE}
library(caret)
library(MASS)
library(rpart)
```
Load the data files and delete the columns which do not have predictive power or have very little variability (date, username, N/A etc)
```{r}
data_train_1=read.csv("pml-training.csv",header = TRUE,sep = ",")
data_test_1=read.csv("pml-testing.csv",header = TRUE,sep = ",")

data_train=data_train_1[,c(7,8,9,10,11,37:49,60:68,84:86,102,113:124,140,151:160)]
data_test=data_test_1[,c(7,8,9,10,11,37:49,60:68,84:86,102,113:124,140,151:159)]
```
Use all the variables as predictors using "rpart"
```{r}
modFit=rpart(classe~.,data=data_train)
pred = predict(modFit, type="class")
tab=table(pred,data_train$classe)
#create confusion matrix to verify in sample prediction power
confusionMatrix(tab)
#predict test data using the trained model
predict(modFit, type="class",newdata=data_test)
```
Use "lda"
```{r}
modFit_lda=lda(classe~.,data=data_train)
#create confusion matrix to verify in sample prediction power
model <- predict(modFit_lda)$class
conf=table(model,data_train$class)
confusionMatrix(conf)
#predict test data using the trained model
predict(modFit_lda,newdata=data_test)
```
using rf 
```{r}
intrain=createDataPartition(y=data_train$classe,p=.7,list = FALSE)
training=data_train[intrain,] 
testing=data_train[-intrain,]

ctrl <- trainControl(allowParallel=T, method="cv", number=4)

modFit_rf=train(classe~roll_dumbbell+yaw_dumbbell+pitch_dumbbell+total_accel_dumbbell+gyros_dumbbell_x+gyros_dumbbell_y+gyros_dumbbell_z+accel_dumbbell_x+accel_dumbbell_y+accel_dumbbell_z+magnet_dumbbell_x+magnet_dumbbell_x+
               magnet_dumbbell_y+magnet_dumbbell_z,method="rf",data=training,trControl=ctrl)
table(predict(modFit_rf,newdata=testing),testing$classe)

predict(modFit_rf,newdata=data_test)
``` 
